apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-consolein
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtc-consolein
  template:
    metadata:
      labels:
        app: rtc-consolein
    spec:
      containers:
      - name: container-consolein
        image: kuroseaist/consolein:1.1
        tty: true
        stdin: true
        command:
          - /work/ConsoleInComp
        args:
          - "-o"
          - "corba.nameservers:10.96.0.100"
          - "-o"
          - "manager.components.preactivation:ConsoleIn0"
          - "-o"
          - "port.outport.out.publish_topic: data_topic"
      nodeSelector:
        consolein: "true"
