apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-consoleout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtc-consoleout
  template:
    metadata:
      labels:
        app: rtc-consoleout
    spec:
      containers:
      - name: container-consoleout
        image: kuroseaist/consoleout:1.0
        command:
          - /work/ConsoleOutComp
        args:
          - "-o"
          - "corba.nameservers:10.96.0.100"
          - "-o"
          - "manager.components.preactivation:ConsoleOut0"
          - "-o"
          - "port.inport.in.subscribe_topic: data_topic"
      nodeSelector:
        consoleout: "true"
